### ISSUE TITLE
硬币数量不为整数时会报错

### ISSUE THREAD

**Issue by journey-ad** [withsalt/BilibiliLiveTools#1]
```
Unhandled exception. System.Exception: Convert result model failed. Input string '1315.4' is not a valid integer. Path 'data.userCoinIfo.coins', line 1, position 907.
   at Bilibili.Api.LiveApi.GetRoomInfo(User user) in E:\CSharp\Projects\BilibiliLiveTools\src\Bilibili\Api\LiveApi.cs:line 135
   at BilibiliLiveTools.Program.Main(String[] args) in E:\CSharp\Projects\BilibiliLiveTools\src\BilibiliLiveTools\Program.cs:line 63
   at BilibiliLiveTools.Program.<Main>(String[] args)
fish: “sudo ./BilibiliLiveTools” terminated by signal SIGABRT (Abort)
```

**Comment by withsalt** [comment]
已修复。
