### ISSUE TITLE
播了几十分钟后报错

### ISSUE THREAD

**Issue by wangmeng-95** [withsalt/BilibiliLiveTools#26]
2024/09/27 08:10:47.320|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:11:47.316|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:12:47.320|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:13:47.317|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:14:47.311|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:15:47.313|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:16:47.323|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:17:47.308|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:18:35.586|WARN|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|FFmpeg异常退出。
2024/09/27 08:18:35.586|WARN|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|等待30s后重新推流...
2024/09/27 08:18:47.316|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 08:19:07.404|INFO|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|获取推流地址成功，推流地址：rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_541117624_40299736&key=978a7a17e99cbd70acf9bea62f9ea028&schedule=rtmp&pflag=1
2024/09/27 08:19:07.404|INFO|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|ffmpeg推流命令：E:\chromedownload\BilibiliAutoLiver_Windows_x64\runtimes\win-x64\bin\ffmpeg.exe -re -f concat -safe 0 -i "E:\chromedownload\BilibiliAutoLiver_Windows_x64\data\pushfiles.txt" -vcodec libx264 -pix_fmt yuv420p -r 30 -s 1280x720 -g 60 -b:v 5000k -maxrate 5000k -bufsize 10000k -acodec aac -b:a 128k -ar 44100 -preset ultrafast -tune zerolatency -f flv "rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_541133324_4022329736&key=978a7a17e99cbd70acf343a62f9ea028&schedule=rtmp&pflag=1"
2024/09/27 08:19:07.404|INFO|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|推流参数初始化完成，开始推流...
2024/09/27 19:09:14.560|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 19:09:14.560|ERROR|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|心跳定时任务执行失败，不知道这样的主机。 (api.live.bilibili.com:443)
 *****Error***** 
 System.Net.Http.HttpRequestException: 不知道这样的主机。 (api.live.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (11001): 不知道这样的主机。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bilibili.AspNetCore.Apis.Services.HttpClientService.Execute[T](String url, HttpMethod method, Object body, BodyFormat format, Boolean withCookie, String cookie, Boolean getRowData) in D:\Projects\BilibiliLiveTools\src\Bilibili.AspNetCore.Apis\Services\HttpClientService.cs:line 128
   at Bilibili.AspNetCore.Apis.Services.BilibiliAccountApiService.HeartBeat() in D:\Projects\BilibiliLiveTools\src\Bilibili.AspNetCore.Apis\Services\BilibiliAccountApiService.cs:line 266
   at BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob.SendHeartBeat() in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Jobs\Job\SendHeartBeatJob.cs:line 42   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bilibili.AspNetCore.Apis.Services.HttpClientService.Execute[T](String url, HttpMethod method, Object body, BodyFormat format, Boolean withCookie, String cookie, Boolean getRowData) in D:\Projects\BilibiliLiveTools\src\Bilibili.AspNetCore.Apis\Services\HttpClientService.cs:line 128
   at Bilibili.AspNetCore.Apis.Services.BilibiliAccountApiService.HeartBeat() in D:\Projects\BilibiliLiveTools\src\Bilibili.AspNetCore.Apis\Services\BilibiliAccountApiService.cs:line 266
   at BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob.SendHeartBeat() in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Jobs\Job\SendHeartBeatJob.cs:line 42
2024/09/27 19:09:31.728|WARN|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|FFmpeg异常退出。
2024/09/27 19:09:31.728|WARN|BilibiliAutoLiver.Services.PushService.AdvancePushStreamService|等待30s后重新推流...
2024/09/27 19:09:47.312|INFO|BilibiliAutoLiver.Jobs.Job.SendHeartBeatJob|发送心跳请求
2024/09/27 19:11:03.865|INFO|BilibiliAutoLiver.Plugin.Base.IPipeProcess|没有插件需要加载。
2024/09/27 19:11:04.099|INFO|RegisterDatabase|For sqlite, automatic sync database structure is turned on, start seeding database...
2024/09/27 19:11:04.385|INFO|Microsoft.Hosting.Lifetime|Now listening on: http://localhost:5000
2024/09/27 19:11:04.385|INFO|Microsoft.Hosting.Lifetime|Application started. Press Ctrl+C to shut down.
2024/09/27 19:11:04.385|INFO|Microsoft.Hosting.Lifetime|Hosting environment: Production
2024/09/27 19:11:04.385|INFO|Microsoft.Hosting.Lifetime|Content root path: E:\chromedownload\BilibiliAutoLiver_Windows_x64
2024/09/27 19:11:11.949|INFO|Microsoft.Hosting.Lifetime|Application is shutting down...
2024/09/27 19:12:04.511|WARN|Bilibili.AspNetCore.Apis.Services.BilibiliCookieService|The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
2024/09/27 19:12:04.511|ERROR|Bilibili.AspNetCore.Apis.Services.BilibiliAccountApiService|扫码登录失败，Cannot access a disposed object.
Object name: 'IServiceProvider'.
2024/09/27 19:12:04.521|ERROR|BilibiliAutoLiver.Services.StartupService|用户登录失败
 *****Error***** 
 System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.<CheckDisposed>g__Throw|41_0()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.Remove(Object key)
   at Bilibili.AspNetCore.Apis.Services.BilibiliAccountApiService.LoginByQrCode() in D:\Projects\BilibiliLiveTools\src\Bilibili.AspNetCore.Apis\Services\BilibiliAccountApiService.cs:line 219
   at BilibiliAutoLiver.Services.StartupService.Login() in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Services\StartupService.cs:line 75   at Microsoft.Extensions.Caching.Memory.MemoryCache.<CheckDisposed>g__Throw|41_0()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.Remove(Object key)
   at Bilibili.AspNetCore.Apis.Services.BilibiliAccountApiService.LoginByQrCode() in D:\Projects\BilibiliLiveTools\src\Bilibili.AspNetCore.Apis\Services\BilibiliAccountApiService.cs:line 219
   at BilibiliAutoLiver.Services.StartupService.Login() in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Services\StartupService.cs:line 75
2024/09/27 19:12:04.538|ERROR|BilibiliAutoLiver.Services.StartupService|初始化失败！
 *****Error***** 
 System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.<CheckDisposed>g__Throw|41_0()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.Remove(Object key)
   at BilibiliAutoLiver.Services.StartupService.Login() in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Services\StartupService.cs:line 110
   at BilibiliAutoLiver.Services.StartupService.Start(CancellationToken token) in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Services\StartupService.cs:line 43   at Microsoft.Extensions.Caching.Memory.MemoryCache.<CheckDisposed>g__Throw|41_0()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.Remove(Object key)
   at BilibiliAutoLiver.Services.StartupService.Login() in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Services\StartupService.cs:line 110
   at BilibiliAutoLiver.Services.StartupService.Start(CancellationToken token) in D:\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Services\StartupService.cs:line 43
2024/09/27 19:12:28.998|INFO|BilibiliAutoLiver.Plugin.Base.IPipeProcess|没有插件需要加载。
2024/09/27 19:12:29.212|INFO|RegisterDatabase|For sqlite, automatic sync database structure is turned on, start seeding database...

**Comment by withsalt** [comment]
扫码登录问题已处理，下一版本解决

**Comment by wangmeng-95** [comment]
感谢大佬
