### ISSUE TITLE
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by zhushiyo** [withsalt/BilibiliLiveTools#30]
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at BilibiliAutoLiver.DependencyInjection.RegisterMediaStaticFiles.UseMediaStaticFiles(WebApplication app) in F:\CSharp\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\DependencyInjection\RegisterMediaStaticFiles.cs:line 18
   at BilibiliAutoLiver.Program.Main(String[] args) in F:\CSharp\Projects\BilibiliLiveTools\src\BilibiliAutoLiver\Program.cs:line 111
   at BilibiliAutoLiver.Program.<Main>(String[] args)
Aborted (core dumped)
![S41109-00423550_tech lolli toolbox](https://github.com/user-attachments/assets/ca4b96d2-5d99-4130-97a7-7ea25bde4c3b)

**Comment by withsalt** [comment]
1、检查一下，应用程序根目录配置文件appsettings.json在否存在
2、配置文件appsettings.json中，DataDirectory不能为空
