### ISSUE TITLE
无法正确处理用户信息

### ISSUE THREAD

**Issue by urusai-me** [withsalt/BilibiliLiveTools#5]
SYSTEM INFO
```
Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux 32bit
version 21bfdeee3a6ea823e2113b983390acd1eec8edfb
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

ERROR：
```
Unhandled exception. System.Exception: Convert result model failed. Could not convert string to integer: 2020-06-29. Path 'data.vip_endtime', line 1, position 1015.
   at Bilibili.Api.LiveApi.GetRoomInfo(User user) in E:\CSharp\Projects\Developing\BilibiliLiveTools\src\Bilibili\Api\LiveApi.cs:line 135
   at BilibiliLiveTools.Program.Main(String[] args) in E:\CSharp\Projects\Developing\BilibiliLiveTools\src\BilibiliLiveTools\Program.cs:line 62
   at BilibiliLiveTools.Program.<Main>(String[] args)
```

**Comment by urusai-me** [comment]
话说为啥要处理这个老爷到期时间……

**Comment by urusai-me** [comment]
老爷过期马上就能用了orz~
