### ISSUE TITLE
用户uid长度int装不下了

### ISSUE THREAD

**Issue by oldcai** [withsalt/BilibiliLiveTools#9]
3493134331801111

uid现在都这么长了

**Comment by oldcai** [comment]
```
Unhandled exception. Newtonsoft.Json.JsonReaderException: JSON integer 3493134331801111 is too large or small for an Int32. Path 'data.uid', line 1, position 81.

   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at BilibiliLiver.Utils.JsonUtil.DeserializeJsonToObject[T](String json) in D:\Projects\BilibiliLiveTools\src\BilibiliLiveCommon\Utils\JsonUtil.cs:line 70
   at BilibiliLiveCommon.Services.HttpClientService.Execute[T](String url, HttpMethod method, Object body, BodyFormat format, Boolean withCookie) in D:\Projects\BilibiliLiveTools\src\BilibiliLiveCommon\Services\HttpClientService.cs:line 129
   at BilibiliLiveCommon.Services.BilibiliLiveApiService.GetLiveRoomInfo() in D:\Projects\BilibiliLiveTools\src\BilibiliLiveCommon\Services\BilibiliLiveApiService.cs:line 57
   at BilibiliLiver.Services.ConfigureService.CheckLiveRoom() in D:\Projects\BilibiliLiveTools\src\BilibiliLiver\Services\ConfigureService.cs:line 135
   at BilibiliLiver.Services.ConfigureService.StartAsync(CancellationToken cancellationToken) in D:\Projects\BilibiliLiveTools\src\BilibiliLiver\Services\ConfigureService.cs:line 46

......

   at BilibiliLiver.Program.Main(String[] args) in D:\Projects\BilibiliLiveTools\src\BilibiliLiver\Program.cs:line 18
```

会报以上错误

**Comment by oldcai** [comment]
https://github.com/withsalt/BilibiliLiveTools/blob/7fb7a47cf53a8f11fd7eac2e35534a3479ff0105/src/BilibiliLiveCommon/Model/RoomPlayInfo.cs#L24

将这里改成string或许就可以？

**Comment by withsalt** [comment]
x修改为long吧。json数据结构是数值类型的

**Comment by withsalt** [comment]
已修复
